### ISSUE TITLE
The "Better CSS" package breaks the use of "Goto Definition" from an HTML file.

### ISSUE THREAD

**Issue by pcunite** [facelessuser/sublime-languages#7]
Using ST3 version 3083, I updated the default package with your new version of the CSS package. Doing so removes the option to "Goto Definition" (right click on a class="blah") within an HTML file. Therefore, I simply used your **CSS.tmLanguage** file instead.

**Comment by facelessuser** [comment]
I think the standard CSS is a bit better than this one now.  I don't use CSS a lot as I am not a web programmer.  I should probably remove my custom CSS in favor of the default.  I could re-sync, but with default packages now available on github, I imagine people will start contributing and making them much better.  I would eventually love to eliminate most languages here in favor of supported ones.  But there are a number that I am not yet ready to.

So I will probably just kill off my personal CSS.

**Comment by facelessuser** [comment]
Default syntaxes are much better in recent Sublime builds.  There is no need to keep my own.  Time is better spent contributing to the default open source syntaxes.
