### ISSUE TITLE
Look at removing some languages

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/sublime-languages#8]
By now, there are probably some packages that can better replace languages than some of mine.

I am pretty sure there are better for the following:
- [ ] CSS
- [x] JavaScript
- [x] Perl
- [x] PHP
- [x] Python

I need to confirm this and if so, remove them from this repo.  Ideally, I would love to kill off this repo completely, but we shall see.

I think batch is still fine.

C/C++ may still be fine (I am always looking for a better one of this...sigh).

My markdown is a mess internally, but it still fits my needs.  I'd like to clean this up at some point.

**Comment by facelessuser** [comment]
- Python can be replaced by either PythonImproved or MagicPython.  Though PythonImproved is the spiritual successor of my Python package, I've been playing with MagicPython recently and have been fairly pleased.
- Javascript can be replaced with something like JavaScriptNext which handles a lot of the latest Javascript stuff.  I still like my old JSON highlighter with different key value colors.  Maybe that will come back at least.
- Perl was just a poorly patched default perl to get past some really bad highlighting.  Modern Perl seems much, much better.  This was a no brainer.
- All I did was make non-internal function calls highlight, while I haven't found another package that does this, I don't code in PHP enough to support my own PHP language.  And to be honest, mine is out dated and doesn't support the latest and greatest PHP stuff which is frankly more important.

**Comment by facelessuser** [comment]
- I think the default CSS is now probably better than mine, and probably getting better all the time.  I haven't yet removed CSS, but as soon as I settle on the best replacement, I will remove it and fix #7.

**Comment by facelessuser** [comment]
### Keeping
- I will keep batch as it is better than the default
- I am keeping C/C++ for now.  I may check on the original I forked from.  Maybe merge my stuff back into that.  Before I ditch C/C++, I want to make sure I am not grabbing a package that will grossly deviate from what I want.
- Current Markdown is a mess.  Not sure what to do about it, but I am sticking with it for now.

**Comment by louwers** [comment]
I don't think there is any better C++ highlighter around! 

The hashtag is not coloured though, is that intentional?
![screen shot 2015-10-24 at 2 09 07](https://cloud.githubusercontent.com/assets/649392/10707553/3ba1f06e-79f4-11e5-82b9-4c5664b9de05.png)

**Comment by facelessuser** [comment]
Yeah, that is what I am guessing.  As for the `#`, yeah I kinda liked it that way; maybe it's weird :smile:.

**Comment by louwers** [comment]
Github does it too
```cpp
#include iostream
```
and besides that, this is completely legal:
```cpp
# include <iostream>
```
so maybe it is not so weird after all ;-)

**Comment by facelessuser** [comment]
> so maybe it is not so weird after all (it really is though ;-) ).

Yeah, I thought I'd seen it before in other syntax highlighters.

> By the way, to get an idea: the one you forked it from doesn't even highlight the dereference operator... C Improved is nice for C.

I may have originally, but now it is forked from [this](https://github.com/kodLite/cppStartingKit) one now.  But looking through the issues, it looks like he's changed things and reintroduced new bugs.  I was afraid of such things which is why I continued maintaining my own fork.  No worries, I kinda thought I wouldn't get away from maintaining my own C language, but I thought I'd at least look :smile:.

**Comment by facelessuser** [comment]
With recent improvements in Sublime's default languages, I am dropping C/C++ support.  Probably support for most everything to be honest.  Time is better spent submitting patches to the now open sourced default syntaxes than it is keeping personal ones.
